#!/bin/sh
set -e

: "${NGINX_PORT:=8080}"
: "${NGINX_SSL_PORT:=8443}"
: "${NGINX_ENABLE_SSL:=true}"
: "${NGINX_SSL_CERT_PATH:=/etc/nginx/certs/selfsigned.crt}"
: "${NGINX_SSL_KEY_PATH:=/etc/nginx/certs/selfsigned.key}"
: "${NGINX_SSL_CN:=localhost}"
: "${UPSTREAM_PORT:=3000}"
: "${NGINX_CLIENT_MAX_BODY_SIZE:=100m}"

: "${NEXT_PUBLIC_APP_NAME:=Live Clipboard}"
if [ -z "${NEXT_PUBLIC_APP_URL}" ]; then
	if [ "${NGINX_ENABLE_SSL}" = "true" ]; then
		NEXT_PUBLIC_APP_URL="https://localhost:${NGINX_SSL_PORT}"
	else
		NEXT_PUBLIC_APP_URL="http://localhost:${NGINX_PORT}"
	fi
fi
: "${NEXT_PUBLIC_ENABLE_ANALYTICS:=false}"
: "${NEXT_PUBLIC_ENABLE_ERROR_TRACKING:=false}"
: "${NEXT_PUBLIC_MAX_PEER_CONNECTIONS:=10}"
: "${NEXT_PUBLIC_PEER_CONNECTION_TIMEOUT:=30000}"
: "${NEXT_PUBLIC_MAX_FILE_SIZE:=104857600}"
: "${NEXT_PUBLIC_CHUNK_SIZE:=16384}"
: "${NEXT_PUBLIC_CLIPBOARD_SYNC_INTERVAL:=1000}"
: "${NEXT_PUBLIC_MAX_CLIPBOARD_SIZE:=1048576}"
: "${NEXT_PUBLIC_GA_ID:=}"
: "${NEXT_PUBLIC_POSTHOG_KEY:=}"

export NGINX_PORT NGINX_SSL_PORT NGINX_ENABLE_SSL NGINX_SSL_CERT_PATH NGINX_SSL_KEY_PATH NGINX_SSL_CN UPSTREAM_PORT NGINX_CLIENT_MAX_BODY_SIZE
export NEXT_PUBLIC_APP_NAME NEXT_PUBLIC_APP_URL NEXT_PUBLIC_ENABLE_ANALYTICS
export NEXT_PUBLIC_ENABLE_ERROR_TRACKING NEXT_PUBLIC_MAX_PEER_CONNECTIONS
export NEXT_PUBLIC_PEER_CONNECTION_TIMEOUT NEXT_PUBLIC_MAX_FILE_SIZE
export NEXT_PUBLIC_CHUNK_SIZE NEXT_PUBLIC_CLIPBOARD_SYNC_INTERVAL
export NEXT_PUBLIC_MAX_CLIPBOARD_SIZE NEXT_PUBLIC_GA_ID NEXT_PUBLIC_POSTHOG_KEY

if [ "${NGINX_ENABLE_SSL}" = "true" ]; then
	mkdir -p "$(dirname "${NGINX_SSL_CERT_PATH}")"
	if [ ! -f "${NGINX_SSL_CERT_PATH}" ] || [ ! -f "${NGINX_SSL_KEY_PATH}" ]; then
		echo "[NGINX] Generating self-signed certificate for CN=${NGINX_SSL_CN}"
		openssl req -x509 -nodes -newkey rsa:2048 \
			-keyout "${NGINX_SSL_KEY_PATH}" \
			-out "${NGINX_SSL_CERT_PATH}" \
			-days 365 \
			-subj "/CN=${NGINX_SSL_CN}"
	fi

	envsubst '$NGINX_PORT $NGINX_SSL_PORT $NGINX_SSL_CERT_PATH $NGINX_SSL_KEY_PATH $UPSTREAM_PORT $NGINX_CLIENT_MAX_BODY_SIZE' \
		< /etc/nginx/nginx.conf.ssl.template > /etc/nginx/nginx.conf
else
	envsubst '$NGINX_PORT $UPSTREAM_PORT $NGINX_CLIENT_MAX_BODY_SIZE' \
		< /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
fi

envsubst '$NEXT_PUBLIC_APP_NAME $NEXT_PUBLIC_APP_URL $NEXT_PUBLIC_ENABLE_ANALYTICS \
$NEXT_PUBLIC_ENABLE_ERROR_TRACKING $NEXT_PUBLIC_MAX_PEER_CONNECTIONS \
$NEXT_PUBLIC_PEER_CONNECTION_TIMEOUT $NEXT_PUBLIC_MAX_FILE_SIZE \
$NEXT_PUBLIC_CHUNK_SIZE $NEXT_PUBLIC_CLIPBOARD_SYNC_INTERVAL \
$NEXT_PUBLIC_MAX_CLIPBOARD_SIZE $NEXT_PUBLIC_GA_ID $NEXT_PUBLIC_POSTHOG_KEY' \
	< /app/runtime-env.template.js > /app/public/runtime-env.js

nginx

exec su-exec nextjs node /app/server.js
