'use client';

import React, { useState, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { CopyButton } from '@/components/CopyButton';
import { SignalDataDisplay } from './SignalDataDisplay';
import { SignalDataInput } from './SignalDataInput';
import type { SignalData } from '@/types';
import toast from 'react-hot-toast';
import { AlertCircle, CheckCircle2, Info } from 'lucide-react';

/**
 * Props for PeerConnectionExchange component
 */
export interface PeerConnectionExchangeProps {
  /**
   * Whether the current peer is the initiator
   */
  isInitiator: boolean;

  /**
   * Callback when local signal data is generated
   */
  onLocalSignal: (signalData: SignalData) => void;

  /**
   * Callback when remote signal data is received
   */
  onRemoteSignal: (signalData: SignalData) => void;

  /**
   * Current connection state
   */
  connectionState?: 'disconnected' | 'connecting' | 'connected' | 'failed';

  /**
   * Whether to show the component
   */
  show?: boolean;

  /**
   * Custom class name
   */
  className?: string;
}

/**
 * Connection step type for tracking progress
 */
type ConnectionStep = 'idle' | 'waiting' | 'exchanging' | 'connecting' | 'connected' | 'failed';

/**
 * PeerConnectionExchange Component
 *
 * Provides UI for manually exchanging WebRTC peer connection strings
 * when automatic signaling isn't available.
 */
export function PeerConnectionExchange({
  isInitiator,
  onLocalSignal,
  onRemoteSignal,
  connectionState = 'disconnected',
  show = true,
  className = '',
}: PeerConnectionExchangeProps) {
  const [localSignal, setLocalSignal] = useState<SignalData | null>(null);
  const [remoteSignal, setRemoteSignal] = useState<SignalData | null>(null);
  const [currentStep, setCurrentStep] = useState<ConnectionStep>('idle');
  const [error, setError] = useState<string | null>(null);

  // Handle when signal data is generated by the peer connection
  const handleSignalGenerated = useCallback((signalData: SignalData) => {
    setLocalSignal(signalData);
    setCurrentStep('waiting');

    // Notify parent component
    onLocalSignal(signalData);

    toast.success(
      isInitiator
        ? 'Offer generated! Share this with your peer.'
        : 'Answer generated! Share this with your peer.'
    );
  }, [isInitiator, onLocalSignal]);

  // Handle when user submits remote signal data
  const handleRemoteSignalSubmit = useCallback((signalData: SignalData) => {
    try {
      setRemoteSignal(signalData);
      setError(null);

      // Notify parent component to establish connection
      onRemoteSignal(signalData);

      setCurrentStep('connecting');
      toast.success('Signal data submitted! Connecting...');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Invalid signal data';
      setError(errorMessage);
      toast.error(errorMessage);
      setCurrentStep('failed');
    }
  }, [onRemoteSignal]);

  // Update connection step based on connection state
  React.useEffect(() => {
    if (connectionState === 'connected') {
      setCurrentStep('connected');
    } else if (connectionState === 'failed') {
      setCurrentStep('failed');
      setError('Connection failed. Please try again.');
    } else if (connectionState === 'connecting' && currentStep !== 'connected') {
      setCurrentStep('connecting');
    }
  }, [connectionState, currentStep]);

  // Don't render if not shown
  if (!show) {
    return null;
  }

  // Determine instructions based on role
  const getInstructions = () => {
    if (isInitiator) {
      return {
        title: 'Connect to Peer (Initiator)',
        description: 'Share your offer string and paste your peer\'s answer to establish a connection.',
        steps: [
          { step: 1, text: 'Copy your offer string below' },
          { step: 2, text: 'Share it with your peer (chat, email, etc.)' },
          { step: 3, text: 'Wait for your peer to send you their answer' },
          { step: 4, text: 'Paste their answer in the input field' },
        ],
      };
    } else {
      return {
        title: 'Connect to Peer (Receiver)',
        description: 'Paste the initiator\'s offer, then share your answer to establish a connection.',
        steps: [
          { step: 1, text: 'Paste the offer string from the initiator' },
          { step: 2, text: 'Copy your generated answer string' },
          { step: 3, text: 'Share it with the initiator' },
        ],
      };
    }
  };

  const instructions = getInstructions();

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          {instructions.title}
          {currentStep === 'connected' && (
            <CheckCircle2 className="h-5 w-5 text-green-500" />
          )}
          {currentStep === 'failed' && (
            <AlertCircle className="h-5 w-5 text-destructive" />
          )}
        </CardTitle>
        <CardDescription>
          {instructions.description}
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Connection Steps */}
        {currentStep !== 'connected' && currentStep !== 'failed' && (
          <div className="bg-muted/50 rounded-lg p-4 space-y-2">
            <div className="flex items-start gap-2 text-sm">
              <Info className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
              <div className="space-y-1">
                <p className="font-medium">How to connect:</p>
                <ol className="space-y-1 ml-4">
                  {instructions.steps.map((s) => (
                    <li key={s.step} className="text-muted-foreground">
                      {s.step}. {s.text}
                    </li>
                  ))}
                </ol>
              </div>
            </div>
          </div>
        )}

        {/* Error Display */}
        {error && (
          <div className="bg-destructive/10 border border-destructive text-destructive px-4 py-3 rounded-md flex items-start gap-2">
            <AlertCircle className="h-4 w-4 mt-0.5 flex-shrink-0" />
            <div className="flex-1">
              <p className="font-medium text-sm">Connection Error</p>
              <p className="text-sm mt-1">{error}</p>
            </div>
          </div>
        )}

        {/* Success Message */}
        {currentStep === 'connected' && (
          <div className="bg-green-500/10 border border-green-500 text-green-700 dark:text-green-400 px-4 py-3 rounded-md flex items-start gap-2">
            <CheckCircle2 className="h-4 w-4 mt-0.5 flex-shrink-0" />
            <div className="flex-1">
              <p className="font-medium text-sm">Connection Established!</p>
              <p className="text-sm mt-1">
                You can now share files and clipboard content with your peer.
              </p>
            </div>
          </div>
        )}

        {/* Local Signal Display (Offer or Answer) */}
        {localSignal && (
          <SignalDataDisplay
            signalData={localSignal}
            label={isInitiator ? 'Your Offer String' : 'Your Answer String'}
            description={isInitiator
              ? 'Share this offer with your peer'
              : 'Share this answer with the initiator'
            }
          />
        )}

        {/* Remote Signal Input */}
        {(currentStep === 'waiting' || currentStep === 'exchanging') && (
          <SignalDataInput
            label={isInitiator ? "Paste Peer's Answer" : "Paste Initiator's Offer"}
            description={isInitiator
              ? 'Paste the answer string from your peer'
              : 'Paste the offer string from the initiator'
            }
            onSubmit={handleRemoteSignalSubmit}
            disabled={false}
          />
        )}

        {/* Connection Status */}
        {currentStep === 'connecting' && (
          <div className="flex items-center justify-center gap-2 text-muted-foreground py-4">
            <div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent" />
            <span className="text-sm">Establishing connection...</span>
          </div>
        )}

        {/* Reset Button (for failed connections) */}
        {currentStep === 'failed' && (
          <div className="flex justify-center">
            <Button
              variant="outline"
              onClick={() => {
                setLocalSignal(null);
                setRemoteSignal(null);
                setCurrentStep('idle');
                setError(null);
              }}
            >
              Try Again
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

/**
 * Hook to manage peer connection exchange
 */
export function usePeerConnectionExchange() {
  const [localSignal, setLocalSignal] = useState<SignalData | null>(null);
  const [remoteSignal, setRemoteSignal] = useState<SignalData | null>(null);

  const generateSignal = useCallback((signalData: SignalData) => {
    setLocalSignal(signalData);
  }, []);

  const receiveSignal = useCallback((signalData: SignalData) => {
    setRemoteSignal(signalData);
  }, []);

  const reset = useCallback(() => {
    setLocalSignal(null);
    setRemoteSignal(null);
  }, []);

  return {
    localSignal,
    remoteSignal,
    generateSignal,
    receiveSignal,
    reset,
  };
}

export default PeerConnectionExchange;
